# Generated by Django 5.2.5 on 2025-09-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='avreb',
        ),
        migrations.AddField(
            model_name='department',
            name='abrev',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
